language: python3

python:
    - "3.7"

install:
    - python3 -m pip install --upgrade pip || python -m pip install --upgrade pip
    - pip3 install pipenv
    - pipenv install

notifications:
    slack:
        on_success: always # default: change
        on_failure: always # default: always

    email:
        recipients:
            - eb808826@gmail.com

script:
    - flake8
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test